### PR TITLE
adarsh.j@mulearn

### PR DESCRIPTION
**Pull request by adarsh4j**

### CODE REVIEW

**Review by vishakh-abhayan — CHANGES_REQUESTED** [review]
Don't need to delete that `TEMPLATE.md` file, plesase create that `.md` file on `/proflies` folder

**Comment by adarsh4j** [comment]
Ok

**Comment by adarsh4j** [comment]
I restore template.md and create .md file on /profile folder

**Comment by adarsh4j** [comment]
is it ok or not

**Comment by vishakh-abhayan** [comment]
> I restore template.md and create .md file on /profile folder

 `TEMPLATE.md`, is  deleted that and created new `template.md` and filled it with your details

**Pull request closed without merging**
